### PR TITLE
fix(windows): fix parsing of UTF-16 codepoints in eventFromRecord

### PR DESCRIPTION
**Pull request by neurocyte**
I'm not 100% certian that this is water tight. But I've tested it quite a bit and it seems to work fine.

### CODE REVIEW

**Comment by neurocyte** [comment]
Hmm, looks like I might have broken ESC code handling.

**Comment by neurocyte** [comment]
This breaks shifted characters too.

**Comment by neurocyte** [comment]
Ok. Now it looks like everything is working properly again.

**Comment by rockorager** [comment]
Thanks!

**Pull request merged**
