### PR TITLE
feat: adds `gap_buffer.zig` for `TextInput`

### PR DESCRIPTION
**Pull request by ryleelyman**
i'm not sure of the best place for `gap_buffer.zig` to live. definitely don't mind putting it in this repository, but maybe it might make sense as its own thing, since it's pretty general-purpose? your thoughts would be very much appreciated. also tweaked `TextInput` to use a `GapBuffer(u8)` to manage its text. it _is_ maybe possible for temporarily silly things to happen if a user intentionally combines two previously-separate graphemes into a single one somehow? this is because in order to avoid unnecessary O(n) copies, i assume that the gap is always well-aligned to grapheme boundaries. i haven't had a chance to take this for a spin yet, since my program maybe wants the "Multi" version of GapBuffer too... the gap_buffer.zig file passes all of the tests (which are adapted from the `std.ArrayList` tests), so it ought to "just work", but thought you should know.

### CODE REVIEW

**Comment by rockorager** [comment]
This didn't build initially, but it's just error handling and a couple calls to `secondHalf`. I haven't tried pushing to your branch but this is the diff that makes it build:

```diff
diff --git a/src/widgets/TextInput.zig b/src/widgets/TextInput.zig
index d4efb409f0c4..88bf300ea080 100644
--- a/src/widgets/TextInput.zig
+++ b/src/widgets/TextInput.zig
@@ -34,10 +34,10 @@ pub fn update(self: *TextInput, event: Event) !void {
         .key_press => |key| {
             if (key.matches(Key.backspace, .{})) {
                 if (self.cursor_idx == 0) return;
-                self.deleteBeforeCursor();
+                try self.deleteBeforeCursor();
             } else if (key.matches(Key.delete, .{}) or key.matches('d', .{ .ctrl = true })) {
                 if (self.cursor_idx == self.grapheme_count) return;
-                self.deleteAtCursor();
+                try self.deleteAtCursor();
             } else if (key.matches(Key.left, .{}) or key.matches('b', .{ .ctrl = true })) {
                 if (self.cursor_idx > 0) self.cursor_idx -= 1;
             } else if (key.matches(Key.right, .{}) or key.matches('f', .{ .ctrl = true })) {
@@ -47,9 +47,9 @@ pub fn update(self: *TextInput, event: Event) !void {
             } else if (key.matches('e', .{ .ctrl = true })) {
                 self.cursor_idx = self.grapheme_count;
             } else if (key.matches('k', .{ .ctrl = true })) {
-                self.deleteToEnd();
+                try self.deleteToEnd();
             } else if (key.matches('u', .{ .ctrl = true })) {
-                self.deleteToStart();
+                try self.deleteToStart();
             } else if (key.text) |text| {
                 try self.buf.insertSliceBefore(self.byteOffsetToCursor(), text);
                 self.cursor_idx += 1;
@@ -121,22 +121,22 @@ fn byteOffsetToCursor(self: TextInput) usize {
     return offset;
 }
 
-fn deleteToEnd(self: *TextInput) void {
+fn deleteToEnd(self: *TextInput) !void {
     self.cursor_idx += 1;
     const offset = self.byteOffsetToCursor();
-    self.buf.replaceRangeAfter(offset, self.buf.realLength(), &.{});
+    try self.buf.replaceRangeAfter(offset, self.buf.realLength(), &.{});
     self.grapheme_count = self.cursor_idx;
     self.cursor_idx -= 1;
 }
 
-fn deleteToStart(self: *TextInput) void {
+fn deleteToStart(self: *TextInput) !void {
     const offset = self.byteOffsetToCursor();
-    self.buf.replaceRangeBefore(0, offset, &.{});
+    try self.buf.replaceRangeBefore(0, offset, &.{});
     self.grapheme_count -= self.cursor_idx;
     self.cursor_idx = 0;
 }
 
-fn deleteBeforeCursor(self: *TextInput) void {
+fn deleteBeforeCursor(self: *TextInput) !void {
     // assumption! the gap is never in the middle of a grapheme
     // one way to _ensure_ this is to move the gap... but that's a cost we probably don't want to pay.
     var iter = GraphemeIterator.init(self.buf.items);
@@ -144,7 +144,7 @@ fn deleteBeforeCursor(self: *TextInput) void {
     var i: usize = 1;
     while (iter.next()) |grapheme| {
         if (i == self.cursor_idx) {
-            self.buf.replaceRangeBefore(offset, grapheme.len, &.{});
+            try self.buf.replaceRangeBefore(offset, grapheme.len, &.{});
             self.cursor_idx -= 1;
             self.grapheme_count -= 1;
             return;
@@ -152,10 +152,10 @@ fn deleteBeforeCursor(self: *TextInput) void {
         offset += grapheme.len;
         i += 1;
     } else {
-        var second_iter = GraphemeIterator.init(self.secondHalf());
+        var second_iter = GraphemeIterator.init(self.buf.secondHalf());
         while (second_iter.next()) |grapheme| {
             if (i == self.cursor_idx) {
-                self.buf.replaceRangeBefore(offset, grapheme.len, &.{});
+                try self.buf.replaceRangeBefore(offset, grapheme.len, &.{});
                 self.cursor_idx -= 1;
                 self.grapheme_count -= 1;
                 return;
@@ -166,7 +166,7 @@ fn deleteBeforeCursor(self: *TextInput) void {
     }
 }
 
-fn deleteAtCursor(self: *TextInput) void {
+fn deleteAtCursor(self: *TextInput) !void {
     // assumption! the gap is never in the middle of a grapheme
     // one way to _ensure_ this is to move the gap... but that's a cost we probably don't want to pay.
     var iter = GraphemeIterator.init(self.buf.items);
@@ -174,17 +174,17 @@ fn deleteAtCursor(self: *TextInput) void {
     var i: usize = 1;
     while (iter.next()) |grapheme| {
         if (i == self.cursor_idx + 1) {
-            self.buf.replaceRangeAfter(offset, grapheme.len, &.{});
+            try self.buf.replaceRangeAfter(offset, grapheme.len, &.{});
             self.grapheme_count -= 1;
             return;
         }
         offset += grapheme.len;
         i += 1;
     } else {
-        var second_iter = GraphemeIterator.init(self.secondHalf());
+        var second_iter = GraphemeIterator.init(self.buf.secondHalf());
         while (second_iter.next()) |grapheme| {
             if (i == self.cursor_idx + 1) {
-                self.buf.replaceRangeAfter(offset, grapheme.len, &.{});
+                try self.buf.replaceRangeAfter(offset, grapheme.len, &.{});
                 self.grapheme_count -= 1;
                 return;
             }
```

**Comment by rockorager** [comment]
Yeah I'm not sure if this living in vaxis is ideal?? Someone has done some extra work on the [Queue implementation](https://hg.sr.ht/~nmichaels/threadsafeq) I wrote and published as a separate lib as well, maybe something like that for this would be better for portability...for the Queue at least I still have it vendored (and probably will keep it that way since it's so small and simple).

I wonder if the gap buffer is something that could be in `std` at some point?

Anyways - awesome work. My initial testing has an assertion failure but I haven't debugged yet. I hit it when I paste "👩‍🚀" six times in the textinput

**Comment by ryleelyman** [comment]
thanks for the catch! the problem was that i failed to adjust the starting point of the second half when `allocator.resize` succeeds. added a test to `TextInput` that covers this precise testing haha.

i'll throw up a `GapBuffer` repository now :)

**Comment by rockorager** [comment]
> tada! it's here: https://github.com/ryleelyman/GapBuffer.zig

Awesome!

> happy to add the relevant stuff to `build.zig` in case you'd prefer a straight-up dependency :)

Yeah let's go that route. Thanks again!

**Comment by ryleelyman** [comment]
great! should be ready to merge! still running into the weird "integer bit width out of range" error when trying to run the tests...

**Pull request merged**
