### PR TITLE
feat: add setTerminalWorkingDirectory (OSC7)

### PR DESCRIPTION
**Pull request by neurocyte**

### CODE REVIEW

**Comment by rockorager** [comment]
Just want to make sure I understand the use case. I assume you are changing the working directory in flow, and want the terminal to be aware for launching different terminals open in the same working directory?

**Comment by neurocyte** [comment]
Yes, that is correct.

**Comment by rockorager** [comment]
> Is there an issue with this commit? It seems to be working well in flow.

I left a comment above about percent encoding. I think we really only need to percent encode '\\' and control bytes (0x00 - 0x1F)

**Comment by neurocyte** [comment]
> I left a comment above about percent encoding.

Strange. I don't see any comments.

**Pull request merged**
