### PR TITLE
Introduce new standard widgets

### PR DESCRIPTION
**Pull request by Cloudef**
2024-06-01-002648_hyprshot

Scrolling is a very common need in CLI applications. The ScrollView widget allows you to implement a scrollable content trivially. Provided is also a TextView for showing text content which is also a common task. It is not covered in this PR, but it would be nice if TextView could wrap the rendered text in future.

CodeView is something I had already laying around. It could be useful for showing more code like content and provide as a good starting point for writing your own editor widget.

### CODE REVIEW

**Comment by Cloudef** [comment]
Example code that styles a zig source code buffer for the CodeView or TextView
```zig
const std = @import("std");
const Buffer = @import("../Spurdo.zig").Buffer;

const CommentState = packed struct(u16) {
    const Phase = enum(u8) {
        searching,
        maybe,
        found,
    };

    byte: u8 = 0,
    phase: Phase = .searching,

    pub fn init(byte: u8, phase: Phase) @This() {
        return .{ .byte = byte, .phase = phase };
    }

    pub fn asInt(byte: u8, phase: Phase) u16 {
        return @This().init(byte, phase).int();
    }

    pub fn int(self: @This()) u16 {
        return @bitCast(self);
    }
};

pub fn style(allocator: std.mem.Allocator, buffer: *Buffer) !void {
    var comment_parser: CommentState = .{};
    var comment_begin: usize = 0;
    for (buffer.content.items, 0..) |b, index| {
        if (comment_parser.phase == .found) {
            if (b == '\n') {
                comment_parser.phase = .searching;
                try buffer.updateStyle(allocator, .{
                    .begin = comment_begin,
                    .end = index,
                    .style = .{ .dim = true },
                });
            }
        } else {
            comment_parser.byte = b;
            switch (comment_parser.int()) {
                CommentState.asInt('/', .searching) => {
                    comment_parser.phase = .maybe;
                    comment_begin = index;
                },
                CommentState.asInt('/', .maybe) => comment_parser.phase = .found,
                else => comment_parser.phase = .searching,
            }
        }
    }

    try buffer.content.append(allocator, 0);
    defer _ = buffer.content.pop();
    var ast = try std.zig.Ast.parse(allocator, @ptrCast(buffer.content.items[0 .. buffer.content.items.len - 1]), .zig);
    defer ast.deinit(allocator);

    for (ast.tokens.items(.tag), 0..) |tag, index| {
        if (tag.lexeme()) |name| {
            if (std.zig.Token.keywords.has(name)) {
                const range = ast.tokenToSpan(@intCast(index));
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 5 } },
                });
                continue;
            }
        }
        switch (tag) {
            .doc_comment, .container_doc_comment => {
                const range = ast.tokenToSpan(@intCast(index));
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .dim = true, .bold = true },
                });
            },
            .comma, .colon, .semicolon => {
                const range = ast.tokenToSpan(@intCast(index));
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 6 } },
                });
            },
            .period,
            .period_asterisk,
            .question_mark,
            .bang,
            .ampersand,
            .ampersand_equal,
            .tilde,
            .slash,
            .slash_equal,
            .equal,
            .equal_equal,
            .plus,
            .plus_plus,
            .plus_equal,
            .plus_percent,
            .plus_percent_equal,
            .plus_pipe,
            .plus_pipe_equal,
            .minus,
            .minus_equal,
            .minus_percent,
            .minus_percent_equal,
            .minus_pipe,
            .minus_pipe_equal,
            .asterisk,
            .asterisk_equal,
            .asterisk_asterisk,
            .asterisk_percent,
            .asterisk_percent_equal,
            .asterisk_pipe,
            .asterisk_pipe_equal,
            .percent,
            .percent_equal,
            .pipe,
            .pipe_pipe,
            .pipe_equal,
            .equal_angle_bracket_right,
            .bang_equal,
            .caret,
            .caret_equal,
            .angle_bracket_left,
            .angle_bracket_left_equal,
            .angle_bracket_angle_bracket_left,
            .angle_bracket_angle_bracket_left_equal,
            .angle_bracket_angle_bracket_left_pipe,
            .angle_bracket_angle_bracket_left_pipe_equal,
            .angle_bracket_right,
            .angle_bracket_right_equal,
            .angle_bracket_angle_bracket_right,
            .angle_bracket_angle_bracket_right_equal,
            .l_brace,
            .r_brace,
            .l_bracket,
            .r_bracket,
            .l_paren,
            .r_paren,
            => {
                const range = ast.tokenToSpan(@intCast(index));
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 10 } },
                });
            },
            else => {},
        }
    }

    for (ast.nodes.items(.tag), ast.nodes.items(.main_token), 0..) |tag, main_token, index| {
        switch (tag) {
            .field_access => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 6 } },
                });
            },
            .builtin_call, .builtin_call_two, .builtin_call_two_comma, .builtin_call_comma, .@"asm" => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 3 } },
                });
            },
            .struct_init_dot, .struct_init_dot_two, .struct_init_dot_two_comma => {
                var buf: [2]std.zig.Ast.Node.Index = undefined;
                if (ast.fullStructInit(&buf, @intCast(index))) |init| {
                    for (init.ast.fields) |field| {
                        const range = ast.tokenToSpan(ast.firstToken(field) - 2);
                        try buffer.updateStyle(allocator, .{
                            .begin = range.start,
                            .end = range.end,
                            .style = .{ .fg = .{ .index = 11 } },
                        });
                    }
                }
            },
            .container_field_init, .container_field => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 11 } },
                });
            },
            .identifier => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 12 } },
                });
            },
            .string_literal, .multiline_string_literal, .enum_literal, .number_literal, .char_literal => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 2 } },
                });
            },
            .global_var_decl, .local_var_decl, .simple_var_decl, .aligned_var_decl => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 4 } },
                });
            },
            .@"try", .@"catch", .unreachable_literal => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 1 } },
                });
            },
            .@"defer", .@"errdefer" => {
                const range = ast.tokenToSpan(main_token);
                try buffer.updateStyle(allocator, .{
                    .begin = range.start,
                    .end = range.end,
                    .style = .{ .fg = .{ .index = 15 } },
                });
            },
            else => {},
        }
    }
}
```

**Comment by rockorager** [comment]
Thanks for the example code - was just reading through this trying to see how it all works, that will be helpful!

**Comment by rockorager** [comment]
`ScrollView`: So I have content and it's size is 10 wide x 10 tall. I call `draw` with that size and a parent window, presumably with a size lets say 2x2. `draw` sets my max scroll limits, and the restriction window based on the current `scroll`

Then when i call `writeCell`, I am able to loop through my 10x10 entire view but the cells are only written to the underlying screen if they fall within the 2x2 bounding box....do I have that right?

**Comment by Cloudef** [comment]
Indeed, that's how it works. The ScrollView also offers bounds() function to do bounds checking early in case you are doing something expensive in your draw loop or  you are iterating through large content.

**Comment by rockorager** [comment]
Nice additions! These all look awesome and are very useful, thanks!

**Pull request merged**
